# Generated by Django 5.0.6 on 2026-09-01 06:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('document', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chunk',
            name='qdrant_point_id',
        ),
    ]
