# Generated by Django 5.0.6 on 2026-09-02 07:12

import basic.validators.url_validator
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('document', '0002_remove_chunk_qdrant_point_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='content',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='document',
            name='source_url',
            field=models.URLField(blank=True, max_length=2048, validators=[basic.validators.url_validator.SSRFSafeURLValidator()]),
        ),
    ]
