# Generated by Django 5.0.6 on 2026-09-02 02:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='message',
            name='referenced_chunks',
        ),
    ]
