# Generated by Django 5.0.6 on 2026-09-05 15:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0002_remove_message_referenced_chunks'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='tool_name',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='message',
            name='message_type',
            field=models.CharField(choices=[('text', 'Text'), ('error', 'Error'), ('system', 'System'), ('context', 'Context'), ('tool', 'Tool')], default='text', max_length=20),
        ),
    ]
