# Generated by Django 5.0.6 on 2026-09-06 15:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0003_message_tool_name_alter_message_message_type'),
    ]

    operations = [
        migrations.RenameField(
            model_name='message',
            old_name='content',
            new_name='message',
        ),
        migrations.RenameField(
            model_name='message',
            old_name='sender',
            new_name='role',
        ),
        migrations.AddField(
            model_name='conversation',
            name='summary',
            field=models.TextField(blank=True, help_text='Latest session summary, generated on request. Overwritten each time a new summary is created.'),
        ),
        migrations.AlterField(
            model_name='message',
            name='message_type',
            field=models.CharField(choices=[('text', 'Text'), ('error', 'Error'), ('system', 'System'), ('context', 'Context'), ('tool', 'Tool'), ('media', 'Media')], default='text', max_length=20),
        ),
    ]
