# Generated by Django 5.0.6 on 2026-09-10 02:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0005_documentwatch_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='DocumentWatch',
        ),
    ]
